defaults:
  - view_sampler: bounded

name: vigor
roots: [/data/qiwei/nips25/pano_grf]
make_baseline_1: false
augment: true

image_shape: [256, 512]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

max_fov: 100.0

skip_bad_shape: true
near: .45
far: 100.
baseline_scale_bounds: false
shuffle_val: false
test_len: -1
test_chunk_interval: 1

test_datasets:
  - name: vigor
    dis: 30.0

